version: '3.9'
services:
  db: 
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
        - "3307:3306"
  app: 
    build: .
    command: ./entrypoint.sh
    ports: 
      - "3001:3000"
    depends_on:
      - db
      - rabbitmq
      - redis
      - es
    links:
      - db
      - rabbitmq
      - redis
      - es
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
  worker: 
    build: .
    command: ./entrypoint2.sh 
    ports: 
      - "3002:3000"
    depends_on:
      - db
      - rabbitmq
      - redis
      - app
      - es
    links:
      - db
      - rabbitmq
      - redis
      - app
      - es
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
  rset-up: 
    build: .
    command: rake rabbitmq:setup
    restart: on-failure
    ports: 
      - "3003:3000"
    depends_on:
      - db
      - rabbitmq
      - redis
      - app
      - es
    links:
      - db
      - rabbitmq
      - redis
      - app
      - es
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  redis:
    image: 'redis:5-alpine'
    ports:
      - 6379:6379
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node